apiVersion: v1
kind: Service
metadata:
  name: terraria
  namespace: terraria
spec:
  type: NodePort
  ports:
    - name: game
      port: 7777
      protocol: TCP
      targetPort: 7777
      nodePort: 30777
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraria
  namespace: terraria
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: terraria
          resources:
            requests:
              cpu: "500m"
              memory: "768Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
