apiVersion: v1
kind: ConfigMap
metadata:
  name: terraria-serverconfig
  namespace: terraria
data:
  serverconfig.txt: |
    world=/config/Worlds/champagne.wld
    worldname=champagne
    autocreate=2
    difficulty=0
    maxplayers=8
    port=7777
    motd=Bienvenue sur ChampagneDevOps Terraria !
    language=fr-FR
    upnp=0
    npcstream=60
    priority=1
    worldrollbackstokeep=2
