---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: terraria-secret
  namespace: terraria
spec:
  encryptedData:
    PASSWORD: AgBJh/VEqhJuTbm24qsMhFG1jnNfvqHAUl9tdAMnupFZf3szsXbhgc0Z0TweMjHhqTo931XI7nMfxVsFVdTwAgsa4vnt0WLhhAJYxMm7yL262xL6rtovnTdbHEhA6CDWD4NQJykW+LzeuuwQksTFrefFb1rmU5LjKeGBwd/8pdZrqIvaRGHNllyLFEXNpsUSwJITvqr7JbJB+Bp1sASij/0Ws+CjlfydT3ZrXVHBK+8Wxn3XVh98gGgnlhaZKysDfeMy3LV8+aZidKRs5WxkDdx1jhtG8WYGOcq3FJhPtWnplPuEJB4wSSKmnD5XX4CDU+KKmQdj0ve3c/OCOaBeUp5U8PelGoxMu9lKK5Wrwar1KDIybnzaeNU0KPGbkxZDh52VOEI77LXNb1fTOrgisev7Xm0ekCYVlqpbWV1T0SiVB0gT7IiaSa365/HOQl0QCzvgVpGs76Vso2n1dWefZPkFK7X2sIC51Ybp3A/MS2888QFCp/wqsnxFWhCd4VXfb5m1RDf1Ab7cQrBh0Fmh+c+6y/N9Eh3cYhQpXhIvhs4GwTwaKYvZ1zz1b4Qm1k6gpWuwCjLimVVzfqrxL7RTIPovfpTXttRoTt2dxtnDiWBOqUPXPWrUmSw7bldnW7tBoApKWojZJnnTtHt4ZAX0fEqRRQEjC38EqmfFqYWoKM4KOA5HBi+96j6PEwj7y5IpR84v5nV2HPypaA==
  template:
    metadata:
      creationTimestamp: null
      name: terraria-secret
      namespace: terraria
