---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: terraria-secret
  namespace: terraria
spec:
  encryptedData:
    PASSWORD: AgBPk3ZV5ddRyNXW1TOUNRrgRTuK4y7RMx801qkHXv+WLKw7y/e5nfBSnwymDfZzIIV1JET7OkRtYOtvTmBLBikFtLphlfjV+7doaII8+hxP+T+RAiGpVEeYLvgbJrfBentVbRyo2RwIzZSszDQv41ur+hN01ZMM7t9ndq2OlabMaHfuEnF4v3wfIcYp7ygkhCK+IwoGE8L9s4Qrvysn+nmLAwWA6dJkCmdOZwvoGC+HeNYjgFFw34cFgv9wJMYj5709D4YHMg4BFJbWa+UeWqICCBZv3riLj40c2cRinkV3Jizu0cSlG1XtuNdjxMqmrnMeP/GAet1uOT9vHv2eOtCOHGn++egAGf7ZqlJY4A0NyB9DIQ0VHBcDhRXQCesxnfX74ax8uRuITl/9ZAoz1nYHk5lDJLdSnqpz4Ykk+fRZujNYDlRcTy6FhW3c91SiqXY+1/L1Ihsampxy+ca2PzqqJ8gwDFJ8mzDEFXvDfM/KZi7ARmhIzLsEhmKQqtXGxq0encj1iwH7y5ArsX9mQNory/EtUrQ1rX7wfPXcKQsSNXixuwn7Eeanosc9udA30GhCdFsF6G5qbSNt352WNtnF3qEgqVp1jKdSBeK9p8cOopiZMck+fqCpJEBgspkyyeREPWGHBm0Y/H+z9GKCouo6/82lRjtncwo5xwet4tvVqj2H/NIh++aCBUOPen66yUqOKN0nrQla6Q==
  template:
    metadata:
      creationTimestamp: null
      name: terraria-secret
      namespace: terraria
