---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: terraria-secret
  namespace: terraria
spec:
  encryptedData:
    PASSWORD: AgB/wZNcyk75pn52yEaLJSfxfwxut6CSMFUUcjSOhBV8Y9mvBYadeGgIR8eT2R74mHMC4UqbJQTBlGsPy/bUwcSNxYi3HG4zP1P2wzgjdoC9DdMSjAqRY0z7x9MOuBiJph/j5Dj47/7vYch5ERW4uRC0AcErptknY/TlSm7ZEBO6YKq0dI9rp5wmqE1luLfvV6ObTg/3zA99+LmhMstqAe+CBHv1wXXIyqKBpo2oFAFYz2p+nS+/lvNtlmf4BH8btu9CM26aPbu/+zSmjzzbxs3zu80yILLJ3je18eh9ccPH+0i/+wMchscde8eNxXrLlQKtFnicUbDy5seuHb2CZs0ZQwMojqtxjVVG53qpALmAuy+EMMD+L/uSTA9dezlSGfKazVmLZW4CUU69u0P/7b9UcXmhE4BFlJMUv+X6g06vwh13+3JRKAqANPwG5rOg7WOhIkw2DiEma2dY2V6aEehdkjFG3xtbZqaAH1ksZADW1U1Sgrbdnj3TdXTrSPWyY0Mcl6DpnppGeezvoJIkmsVaif7mOx9k62Ktq1CWlnJDzfaGsNRCBHr5aUmiD1mDn2I5NR+D0QQ2H9qxFpBcr6Q0aXEyN33zexSwh9Vi6A+rhGBciZb7l1OPSKVsifBYUeEARlokJC37+NAko33lCh8t4i5HBThFlt6EMlHfrLIfgtUctJhtZwCCyIE33gZaLNg9il4XbDkzkA==
  template:
    metadata:
      creationTimestamp: null
      name: terraria-secret
      namespace: terraria
