apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraria
  namespace: terraria
spec:
  serviceName: terraria
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: terraria
          # linuxserver/terraria : image s6-overlay, PUID/PGID, non-root ready
          image: lscr.io/linuxserver/terraria:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          ports:
            - containerPort: 7777
              name: game
              protocol: TCP
          envFrom:
            - configMapRef:
                name: terraria-config
            - secretRef:
                name: terraria-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 90
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: terraria-data
